sudo: false
dist: trusty
language: c++
compiler:
  - gcc
addons:
  apt:
    packages:
    - libreadline6-dev
    - libncurses5-dev
    - perl
    - clang
    - g++-mingw-w64-i686
    - qemu-system-x86
install:
 - ./.ci/travis-prepare.sh
script:
 - ./.ci/travis-build.sh
env:
 - BRBASE=7.0 CMPLR=gcc
 - BRBASE=7.0 CMPLR=clang
 - BRBASE=7.0 USR_CXXFLAGS=-std=c++11
 - BRBASE=7.0 CMPLR=clang USR_CXXFLAGS=-std=c++11
 - BRBASE=7.0 WINE=32 TEST=NO STATIC=YES
 - BRBASE=7.0 WINE=32 TEST=NO STATIC=NO
 - BRBASE=7.0 RTEMS=4.10 TEST=NO
 - BRBASE=7.0 RTEMS=4.9 TEST=NO
 - BRBASE=3.16
 - BRBASE=3.15
 - BRBASE=3.14
